"""
plots.py — Visualisations for the CAID benchmark and LipNet prediction analysis.

This module contains:
  - ROC and PR curves read from CAID tool output CSVs (multi-level index format)
  - Per-residue confusion matrix labelling (TP/FP/TN/FN)
  - Utilities for IDR region composition analysis

Note on colours: PREDICTOR_COLORS defines a fixed predictor → colour mapping.
Keeping it constant across all plots ensures visual consistency in thesis figures.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import hmean
from sklearn.metrics import auc

# Fixed colours per predictor — do not change between plots for thesis consistency.
# '#1f77b4' (matplotlib default blue) for LIPNet,
# '#ff7f0e' (matplotlib default orange) for AlphaFold binding.
PREDICTOR_COLORS = {
    'LIPNet':            '#1f77b4',
    'alphafold_binding': '#ff7f0e',
}


# ── ROC curves ────────────────────────────────────────────────────────────────

def plot_roc(preds_rocs, ax=None):
    """
    Plot ROC curves from a .roc.csv file generated by CAID.

    Input DataFrame format:
      Read with pd.read_csv(..., index_col=[0], header=[0,1,2]).
      Columns have a multi-level index: (predictor_name, AUC_value, ...).
      droplevel(2) removes the third level to access (name, AUC).

    Why top-10:
      CAID may contain many predictors (>20). Plotting all of them makes the
      figure unreadable. The top-10 by AUC are sufficient to compare LIPNet
      and AlphaFold against reference predictors.

    The dashed diagonal represents the random classifier (AUC=0.5).
    A useful predictor must lie significantly above this line.
    """
    if ax is None:
        fig, ax = plt.subplots()

    # Extract (predictor_name, AUC) pairs and sort by descending AUC
    auc_rocs = sorted(
        preds_rocs.columns.droplevel(2).unique(),
        key=lambda t: t[1], reverse=True
    )[:10]   # top-10 by AUC

    # Reorder DataFrame columns in top-10 order
    rocs = preds_rocs.reindex(list(zip(*auc_rocs))[0], axis=1, level=0)

    # Diagonal line: random classifier (visual reference)
    ax.plot([0, 1], [0, 1], color='k', linestyle='--')

    for p in rocs.columns.get_level_values(0).unique()[:10]:
        ax.plot(*rocs[p].dropna().T.values, label=p, color=PREDICTOR_COLORS.get(p))

    # Build legend with AUC value for each predictor
    pwauc = next(zip(*auc_rocs))   # tuple of names in AUC order
    predictor_names = {'alphafold_binding': 'alphafold_binding', 'LIPNet': 'LIPNet'}
    lhandles, llabels = ax.get_legend_handles_labels()
    leg = ax.legend(
        lhandles,
        [f"{predictor_names.get(l, l)} - AUC: {auc_rocs[pwauc.index(l)][1]}"
         if l in pwauc else l for l in llabels],
        facecolor='w', framealpha=1, edgecolor='w',
        loc='upper center', bbox_to_anchor=(0.5, -0.15), ncol=1, fontsize=14,
    )
    for line in leg.get_lines():
        line.set_linewidth(4)   # thicker lines in legend for readability

    ax.set_xlim(-0.05, 1.05)
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("FPR", fontsize=14)
    ax.set_ylabel("TPR", fontsize=14)
    ax.tick_params(axis='both', labelsize=14)


# ── Precision-Recall curves ───────────────────────────────────────────────────

def plot_pr(pred_prs, sortby='fmax', ax=None):
    """
    Plot Precision-Recall curves from a .pr.csv file generated by CAID.

    Why prefer the PR curve over ROC for this task:
      The dataset is heavily imbalanced (many more non-binding than binding residues).
      Under class imbalance, ROC can be optimistically high even for mediocre predictors.
      The PR curve is more informative because it depends on TP and FP without
      considering TN (numerous and uninformative here).

    The F-max point is the maximum F1-score along the curve: it is the optimal
    threshold of the predictor. It is marked with a white circle on each curve.

    sortby: metric used to rank predictors in the legend.
      'fmax' (default) — F-max: the primary metric used in CAID
      'auc'            — area under the PR curve
      'aps'            — average precision score

    Grey F-score iso-curves allow reading the F1 value at any point in the PR
    plane without additional computation.

    pred_prs: DataFrame read with index_col=[0], header=[0,1,2,3].
    """
    if ax is None:
        fig, ax = plt.subplots()

    # Compute the three ranking metrics for each predictor
    auc_pr  = sorted(pred_prs.columns.droplevel([2, 3]).unique(), key=lambda t: t[1], reverse=True)
    aps_pr  = sorted(pred_prs.columns.droplevel([1, 3]).unique(), key=lambda t: t[1], reverse=True)
    # F-max: maximum of the harmonic mean (Precision, Recall) along the threshold sweep
    fmax_pr = sorted(
        ((p, hmean(pred_prs[p].dropna().values, axis=1).max().round(3))
         for p in pred_prs.columns.get_level_values(0).unique()),
        key=lambda t: t[1], reverse=True,
    )

    sorter      = {'auc': auc_pr, 'aps': aps_pr, 'fmax': fmax_pr}[sortby]
    sorter_name = {'auc': 'AUC',  'aps': 'APS',  'fmax': '$F_{max}$'}[sortby]

    # F-score iso-curves: meshgrid over Precision × Recall, harmonic mean
    # Dashed grey lines show F1 levels from 0.1 to 0.9
    r  = np.linspace(0, 1, 1000)
    fs = hmean(np.array(np.meshgrid(r, r)).T.reshape(-1, 2), axis=1).reshape(1000, 1000)
    cs = ax.contour(r, r, fs, levels=np.linspace(0.1, 1, 10),
                    colors='silver', alpha=0.7, linewidths=1, linestyles='--')
    ax.clabel(cs, inline=True, fmt='%.1f', fontsize=12, manual=[(l, l) for l in cs.levels[:-1]])

    prcs  = pred_prs.reindex(list(zip(*sorter))[0], axis=1, level=0)
    pwauc = next(zip(*sorter))
    predictor_names = {'LIPNet': 'LIPNet', 'alphafold_binding': 'AlphaFold_binding'}

    for p, z in zip(prcs.columns.get_level_values(0).unique()[:10], range(5, 55, 5)):
        # argmax of harmonic mean along the curve = location of the F-max point
        fmax_idx = hmean(prcs[p].dropna().T).argmax()
        lines    = ax.plot(*prcs[p].dropna().T.values, label=p,
                           zorder=55 - z, color=PREDICTOR_COLORS.get(p))
        # White circle with coloured border = F-max point of the predictor
        ax.plot(*prcs[p].dropna().T.values[:, fmax_idx],
                color='w', marker='o', markerfacecolor=lines[0].get_color(),
                markersize=10, zorder=55 - z, linewidth=10)

    lhandles, llabels = ax.get_legend_handles_labels()
    leg = ax.legend(
        lhandles,
        [f"{predictor_names.get(l, l)} - {sorter_name}: {sorter[pwauc.index(l)][1]}"
         if l in pwauc else l for l in llabels],
        facecolor='w', framealpha=1, edgecolor='w',
        loc='upper center', bbox_to_anchor=(0.5, -0.15), ncol=1, fontsize=14,
    )
    for line in leg.get_lines():
        line.set_linewidth(4)

    ax.set_xlim(-0.05, 1.05)
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlabel("Recall", fontsize=14)
    ax.set_ylabel("Precision", fontsize=14)
    ax.tick_params(axis='both', labelsize=14)


# ── Per-residue confusion matrix labelling ───────────────────────────────────

def label_confusion(row, threshold=0.494):
    """
    Assign a TP/FP/TN/FN label to each row of a per-residue DataFrame.

    Expected columns in the DataFrame:
      'lipnet_score' (float) — raw LipNet score for that residue
      'ref_seq'      (str)   — reference annotation: '0', '1' or '-'

    Default threshold 0.494:
      This is the optimal LipNet value reported in the original publication.
      Can be changed by passing threshold=<value> in apply().

    Returns NaN for:
      - Positions outside IDR ('-'): not part of the CAID evaluation
      - Rows with non-string ref_seq: guard against NaN in the DataFrame

    Why this function replaces create_c_m_column100 / create_c_m_column80 / create_c_m_column:
      The three functions in the old _F_plots.py were 100% identical (same signature,
      same body). Pure duplication with no functional difference.
      A parametric function with threshold= makes everything explicit and maintainable.

    Typical usage:
      df['confusion_matrix'] = df.apply(plots.label_confusion, axis=1)
      # or with a custom threshold:
      df['confusion_matrix'] = df.apply(lambda r: plots.label_confusion(r, threshold=0.5), axis=1)
    """
    ref = row.get('ref_seq')
    # Discard unannotated positions or rows with non-string values (NaN from merge)
    if not isinstance(ref, str) or ref == '-':
        return np.nan

    true_label = int(ref)                              # 0 or 1 from reference
    pred_label = int(row['lipnet_score'] >= threshold) # 0 or 1 from prediction

    if pred_label == 1 and true_label == 1:
        return 'TP'   # predicted binding, is binding
    if pred_label == 1 and true_label == 0:
        return 'FP'   # predicted binding, not binding
    if pred_label == 0 and true_label == 0:
        return 'TN'   # predicted non-binding, not binding
    return 'FN'       # predicted non-binding, is binding


# ── Region composition utilities ─────────────────────────────────────────────

def disorder_region_lengths(ref_seq):
    """
    Return the list of lengths of contiguous non-binding IDR blocks ('0') in ref_seq.

    Used to analyse the length distribution of IDR segments in the reference,
    separately from binding segments ('1') and positions outside IDR ('-').

    Example: '---0011100---' → [2] (one '0' block of length 2 before the '1's)

    Equivalent to the old get_disorder_regions.
    """
    lengths, count = [], 0
    for res in ref_seq:
        if res == '0':
            count += 1
        elif count > 0:
            # End of a block: save the length and reset
            lengths.append(count)
            count = 0
    # Edge case: sequence ends with an open '0' block
    if count > 0:
        lengths.append(count)
    return lengths


def binding_fraction(ref_dict):
    """
    Add the 'binding_frac' key to each reference entry:
    fraction of annotated IDR positions ('0' or '1') that are binding ('1').

    Why in-place: ref_dict is already in memory and potentially large.
    Creating a copy just to add a field would waste RAM.

    Equivalent to the old one_perc (renamed: 'one_perc' is not intuitive,
    'binding_fraction' immediately explains what it returns).
    """
    for data in ref_dict.values():
        seq = data['ref_sequence']
        n0  = seq.count('0')   # non-binding IDR residues
        n1  = seq.count('1')   # binding IDR residues
        # Guard against division by zero (proteins with no IDR annotations)
        data['binding_frac'] = round(n1 / (n0 + n1), 2) if (n0 + n1) > 0 else 0.0
    return ref_dict
